/**
 * Gen 3 move effect constants and move-to-effect mapping.
 *
 * Effect IDs from pokeemerald/include/constants/battle_move_effects.h
 * Mapping extracted from pokeemerald/src/data/battle_moves.h
 */

export const enum E {
  HIT = 0,
  SLEEP = 1,
  POISON_HIT = 2,
  ABSORB = 3,
  BURN_HIT = 4,
  FREEZE_HIT = 5,
  PARALYZE_HIT = 6,
  EXPLOSION = 7,
  DREAM_EATER = 8,
  MIRROR_MOVE = 9,
  ATTACK_UP = 10,
  DEFENSE_UP = 11,
  SPEED_UP = 12,
  SPECIAL_ATTACK_UP = 13,
  SPECIAL_DEFENSE_UP = 14,
  ACCURACY_UP = 15,
  EVASION_UP = 16,
  ALWAYS_HIT = 17,
  ATTACK_DOWN = 18,
  DEFENSE_DOWN = 19,
  SPEED_DOWN = 20,
  SPECIAL_ATTACK_DOWN = 21,
  SPECIAL_DEFENSE_DOWN = 22,
  ACCURACY_DOWN = 23,
  EVASION_DOWN = 24,
  HAZE = 25,
  BIDE = 26,
  RAMPAGE = 27,
  ROAR = 28,
  MULTI_HIT = 29,
  CONVERSION = 30,
  FLINCH_HIT = 31,
  RESTORE_HP = 32,
  TOXIC = 33,
  PAY_DAY = 34,
  LIGHT_SCREEN = 35,
  TRI_ATTACK = 36,
  REST = 37,
  OHKO = 38,
  RAZOR_WIND = 39,
  SUPER_FANG = 40,
  DRAGON_RAGE = 41,
  TRAP = 42,
  HIGH_CRITICAL = 43,
  DOUBLE_HIT = 44,
  RECOIL_IF_MISS = 45,
  MIST = 46,
  FOCUS_ENERGY = 47,
  RECOIL = 48,
  CONFUSE = 49,
  ATTACK_UP_2 = 50,
  DEFENSE_UP_2 = 51,
  SPEED_UP_2 = 52,
  SPECIAL_ATTACK_UP_2 = 53,
  SPECIAL_DEFENSE_UP_2 = 54,
  ACCURACY_UP_2 = 55,
  EVASION_UP_2 = 56,
  TRANSFORM = 57,
  ATTACK_DOWN_2 = 58,
  DEFENSE_DOWN_2 = 59,
  SPEED_DOWN_2 = 60,
  SPECIAL_ATTACK_DOWN_2 = 61,
  SPECIAL_DEFENSE_DOWN_2 = 62,
  ACCURACY_DOWN_2 = 63,
  EVASION_DOWN_2 = 64,
  REFLECT = 65,
  POISON = 66,
  PARALYZE = 67,
  ATTACK_DOWN_HIT = 68,
  DEFENSE_DOWN_HIT = 69,
  SPEED_DOWN_HIT = 70,
  SPECIAL_ATTACK_DOWN_HIT = 71,
  SPECIAL_DEFENSE_DOWN_HIT = 72,
  ACCURACY_DOWN_HIT = 73,
  EVASION_DOWN_HIT = 74,
  SKY_ATTACK = 75,
  CONFUSE_HIT = 76,
  TWINEEDLE = 77,
  VITAL_THROW = 78,
  SUBSTITUTE = 79,
  RECHARGE = 80,
  RAGE = 81,
  MIMIC = 82,
  METRONOME = 83,
  LEECH_SEED = 84,
  SPLASH = 85,
  DISABLE = 86,
  LEVEL_DAMAGE = 87,
  PSYWAVE = 88,
  COUNTER = 89,
  ENCORE = 90,
  PAIN_SPLIT = 91,
  SNORE = 92,
  CONVERSION_2 = 93,
  LOCK_ON = 94,
  SKETCH = 95,
  SLEEP_TALK = 97,
  DESTINY_BOND = 98,
  FLAIL = 99,
  SPITE = 100,
  FALSE_SWIPE = 101,
  HEAL_BELL = 102,
  QUICK_ATTACK = 103,
  TRIPLE_KICK = 104,
  THIEF = 105,
  MEAN_LOOK = 106,
  NIGHTMARE = 107,
  MINIMIZE = 108,
  CURSE = 109,
  PROTECT = 111,
  SPIKES = 112,
  FORESIGHT = 113,
  PERISH_SONG = 114,
  SANDSTORM = 115,
  ENDURE = 116,
  ROLLOUT = 117,
  SWAGGER = 118,
  FURY_CUTTER = 119,
  ATTRACT = 120,
  RETURN = 121,
  PRESENT = 122,
  FRUSTRATION = 123,
  SAFEGUARD = 124,
  THAW_HIT = 125,
  MAGNITUDE = 126,
  BATON_PASS = 127,
  PURSUIT = 128,
  RAPID_SPIN = 129,
  SONICBOOM = 130,
  MORNING_SUN = 132,
  SYNTHESIS = 133,
  MOONLIGHT = 134,
  HIDDEN_POWER = 135,
  RAIN_DANCE = 136,
  SUNNY_DAY = 137,
  DEFENSE_UP_HIT = 138,
  ATTACK_UP_HIT = 139,
  ALL_STATS_UP_HIT = 140,
  BELLY_DRUM = 142,
  PSYCH_UP = 143,
  MIRROR_COAT = 144,
  SKULL_BASH = 145,
  TWISTER = 146,
  EARTHQUAKE = 147,
  FUTURE_SIGHT = 148,
  GUST = 149,
  FLINCH_MINIMIZE_HIT = 150,
  SOLAR_BEAM = 151,
  THUNDER = 152,
  TELEPORT = 153,
  BEAT_UP = 154,
  SEMI_INVULNERABLE = 155,
  DEFENSE_CURL = 156,
  SOFTBOILED = 157,
  FAKE_OUT = 158,
  UPROAR = 159,
  STOCKPILE = 160,
  SPIT_UP = 161,
  SWALLOW = 162,
  HAIL = 164,
  TORMENT = 165,
  FLATTER = 166,
  WILL_O_WISP = 167,
  MEMENTO = 168,
  FACADE = 169,
  FOCUS_PUNCH = 170,
  SMELLINGSALT = 171,
  FOLLOW_ME = 172,
  NATURE_POWER = 173,
  CHARGE = 174,
  TAUNT = 175,
  HELPING_HAND = 176,
  TRICK = 177,
  ROLE_PLAY = 178,
  WISH = 179,
  ASSIST = 180,
  INGRAIN = 181,
  SUPERPOWER = 182,
  MAGIC_COAT = 183,
  RECYCLE = 184,
  REVENGE = 185,
  BRICK_BREAK = 186,
  YAWN = 187,
  KNOCK_OFF = 188,
  ENDEAVOR = 189,
  ERUPTION = 190,
  SKILL_SWAP = 191,
  IMPRISON = 192,
  REFRESH = 193,
  GRUDGE = 194,
  SNATCH = 195,
  LOW_KICK = 196,
  SECRET_POWER = 197,
  DOUBLE_EDGE = 198,
  TEETER_DANCE = 199,
  BLAZE_KICK = 200,
  MUD_SPORT = 201,
  POISON_FANG = 202,
  WEATHER_BALL = 203,
  OVERHEAT = 204,
  TICKLE = 205,
  COSMIC_POWER = 206,
  SKY_UPPERCUT = 207,
  BULK_UP = 208,
  POISON_TAIL = 209,
  WATER_SPORT = 210,
  CALM_MIND = 211,
  DRAGON_DANCE = 212,
  CAMOUFLAGE = 213,
}

/**
 * Maps @pkmn/sim move IDs to Emerald's internal effect constants.
 * Moves not present default to E.HIT (0) — basic damaging move.
 * Extracted from pokeemerald/src/data/battle_moves.h
 */
const MOVE_TO_EFFECT: Record<string, E> = {
  karatechop: E.HIGH_CRITICAL,
  doubleslap: E.MULTI_HIT,
  cometpunch: E.MULTI_HIT,
  payday: E.PAY_DAY,
  firepunch: E.BURN_HIT,
  icepunch: E.FREEZE_HIT,
  thunderpunch: E.PARALYZE_HIT,
  guillotine: E.OHKO,
  razorwind: E.RAZOR_WIND,
  swordsdance: E.ATTACK_UP_2,
  gust: E.GUST,
  whirlwind: E.ROAR,
  fly: E.SEMI_INVULNERABLE,
  bind: E.TRAP,
  stomp: E.FLINCH_MINIMIZE_HIT,
  doublekick: E.DOUBLE_HIT,
  jumpkick: E.RECOIL_IF_MISS,
  rollingkick: E.FLINCH_HIT,
  sandattack: E.ACCURACY_DOWN,
  headbutt: E.FLINCH_HIT,
  furyattack: E.MULTI_HIT,
  horndrill: E.OHKO,
  bodyslam: E.PARALYZE_HIT,
  wrap: E.TRAP,
  takedown: E.RECOIL,
  thrash: E.RAMPAGE,
  doubleedge: E.DOUBLE_EDGE,
  tailwhip: E.DEFENSE_DOWN,
  poisonsting: E.POISON_HIT,
  twineedle: E.TWINEEDLE,
  pinmissile: E.MULTI_HIT,
  leer: E.DEFENSE_DOWN,
  bite: E.FLINCH_HIT,
  growl: E.ATTACK_DOWN,
  roar: E.ROAR,
  sing: E.SLEEP,
  supersonic: E.CONFUSE,
  sonicboom: E.SONICBOOM,
  disable: E.DISABLE,
  acid: E.DEFENSE_DOWN_HIT,
  ember: E.BURN_HIT,
  flamethrower: E.BURN_HIT,
  mist: E.MIST,
  icebeam: E.FREEZE_HIT,
  blizzard: E.FREEZE_HIT,
  psybeam: E.CONFUSE_HIT,
  bubblebeam: E.SPEED_DOWN_HIT,
  aurorabeam: E.ATTACK_DOWN_HIT,
  hyperbeam: E.RECHARGE,
  submission: E.RECOIL,
  lowkick: E.LOW_KICK,
  counter: E.COUNTER,
  seismictoss: E.LEVEL_DAMAGE,
  absorb: E.ABSORB,
  megadrain: E.ABSORB,
  leechseed: E.LEECH_SEED,
  growth: E.SPECIAL_ATTACK_UP,
  razorleaf: E.HIGH_CRITICAL,
  solarbeam: E.SOLAR_BEAM,
  poisonpowder: E.POISON,
  stunspore: E.PARALYZE,
  sleeppowder: E.SLEEP,
  petaldance: E.RAMPAGE,
  stringshot: E.SPEED_DOWN,
  dragonrage: E.DRAGON_RAGE,
  firespin: E.TRAP,
  thundershock: E.PARALYZE_HIT,
  thunderbolt: E.PARALYZE_HIT,
  thunderwave: E.PARALYZE,
  thunder: E.THUNDER,
  earthquake: E.EARTHQUAKE,
  fissure: E.OHKO,
  dig: E.SEMI_INVULNERABLE,
  toxic: E.TOXIC,
  confusion: E.CONFUSE_HIT,
  psychic: E.SPECIAL_DEFENSE_DOWN_HIT,
  hypnosis: E.SLEEP,
  meditate: E.ATTACK_UP,
  agility: E.SPEED_UP_2,
  quickattack: E.QUICK_ATTACK,
  rage: E.RAGE,
  teleport: E.TELEPORT,
  nightshade: E.LEVEL_DAMAGE,
  mimic: E.MIMIC,
  screech: E.DEFENSE_DOWN_2,
  doubleteam: E.EVASION_UP,
  recover: E.RESTORE_HP,
  harden: E.DEFENSE_UP,
  minimize: E.MINIMIZE,
  smokescreen: E.ACCURACY_DOWN,
  confuseray: E.CONFUSE,
  withdraw: E.DEFENSE_UP,
  defensecurl: E.DEFENSE_CURL,
  barrier: E.DEFENSE_UP_2,
  lightscreen: E.LIGHT_SCREEN,
  haze: E.HAZE,
  reflect: E.REFLECT,
  focusenergy: E.FOCUS_ENERGY,
  bide: E.BIDE,
  metronome: E.METRONOME,
  mirrormove: E.MIRROR_MOVE,
  selfdestruct: E.EXPLOSION,
  lick: E.PARALYZE_HIT,
  smog: E.POISON_HIT,
  sludge: E.POISON_HIT,
  boneclub: E.FLINCH_HIT,
  fireblast: E.BURN_HIT,
  clamp: E.TRAP,
  swift: E.ALWAYS_HIT,
  skullbash: E.SKULL_BASH,
  spikecannon: E.MULTI_HIT,
  constrict: E.SPEED_DOWN_HIT,
  amnesia: E.SPECIAL_DEFENSE_UP_2,
  kinesis: E.ACCURACY_DOWN,
  softboiled: E.SOFTBOILED,
  hijumpkick: E.RECOIL_IF_MISS,
  glare: E.PARALYZE,
  dreameater: E.DREAM_EATER,
  poisongas: E.POISON,
  barrage: E.MULTI_HIT,
  leechlife: E.ABSORB,
  lovelykiss: E.SLEEP,
  skyattack: E.SKY_ATTACK,
  transform: E.TRANSFORM,
  bubble: E.SPEED_DOWN_HIT,
  dizzypunch: E.CONFUSE_HIT,
  spore: E.SLEEP,
  flash: E.ACCURACY_DOWN,
  psywave: E.PSYWAVE,
  splash: E.SPLASH,
  acidarmor: E.DEFENSE_UP_2,
  crabhammer: E.HIGH_CRITICAL,
  explosion: E.EXPLOSION,
  furyswipes: E.MULTI_HIT,
  bonemerang: E.DOUBLE_HIT,
  rest: E.REST,
  rockslide: E.FLINCH_HIT,
  hyperfang: E.FLINCH_HIT,
  sharpen: E.ATTACK_UP,
  conversion: E.CONVERSION,
  triattack: E.TRI_ATTACK,
  superfang: E.SUPER_FANG,
  slash: E.HIGH_CRITICAL,
  substitute: E.SUBSTITUTE,
  struggle: E.RECOIL,
  sketch: E.SKETCH,
  triplekick: E.TRIPLE_KICK,
  thief: E.THIEF,
  spiderweb: E.MEAN_LOOK,
  mindreader: E.LOCK_ON,
  nightmare: E.NIGHTMARE,
  flamewheel: E.THAW_HIT,
  snore: E.SNORE,
  curse: E.CURSE,
  flail: E.FLAIL,
  conversion2: E.CONVERSION_2,
  aeroblast: E.HIGH_CRITICAL,
  cottonspore: E.SPEED_DOWN_2,
  reversal: E.FLAIL,
  spite: E.SPITE,
  powdersnow: E.FREEZE_HIT,
  protect: E.PROTECT,
  machpunch: E.QUICK_ATTACK,
  scaryface: E.SPEED_DOWN_2,
  faintattack: E.ALWAYS_HIT,
  sweetkiss: E.CONFUSE,
  bellydrum: E.BELLY_DRUM,
  sludgebomb: E.POISON_HIT,
  mudslap: E.ACCURACY_DOWN_HIT,
  octazooka: E.ACCURACY_DOWN_HIT,
  spikes: E.SPIKES,
  zapcannon: E.PARALYZE_HIT,
  foresight: E.FORESIGHT,
  destinybond: E.DESTINY_BOND,
  perishsong: E.PERISH_SONG,
  icywind: E.SPEED_DOWN_HIT,
  detect: E.PROTECT,
  bonerush: E.MULTI_HIT,
  lockon: E.LOCK_ON,
  outrage: E.RAMPAGE,
  sandstorm: E.SANDSTORM,
  gigadrain: E.ABSORB,
  endure: E.ENDURE,
  charm: E.ATTACK_DOWN_2,
  rollout: E.ROLLOUT,
  falseswipe: E.FALSE_SWIPE,
  swagger: E.SWAGGER,
  milkdrink: E.SOFTBOILED,
  spark: E.PARALYZE_HIT,
  furycutter: E.FURY_CUTTER,
  steelwing: E.DEFENSE_UP_HIT,
  meanlook: E.MEAN_LOOK,
  attract: E.ATTRACT,
  sleeptalk: E.SLEEP_TALK,
  healbell: E.HEAL_BELL,
  return: E.RETURN,
  present: E.PRESENT,
  frustration: E.FRUSTRATION,
  safeguard: E.SAFEGUARD,
  painsplit: E.PAIN_SPLIT,
  sacredfire: E.THAW_HIT,
  magnitude: E.MAGNITUDE,
  dynamicpunch: E.CONFUSE_HIT,
  dragonbreath: E.PARALYZE_HIT,
  batonpass: E.BATON_PASS,
  encore: E.ENCORE,
  pursuit: E.PURSUIT,
  rapidspin: E.RAPID_SPIN,
  sweetscent: E.EVASION_DOWN,
  irontail: E.DEFENSE_DOWN_HIT,
  metalclaw: E.ATTACK_UP_HIT,
  vitalthrow: E.VITAL_THROW,
  morningsun: E.MORNING_SUN,
  synthesis: E.SYNTHESIS,
  moonlight: E.MOONLIGHT,
  hiddenpower: E.HIDDEN_POWER,
  crosschop: E.HIGH_CRITICAL,
  twister: E.TWISTER,
  raindance: E.RAIN_DANCE,
  sunnyday: E.SUNNY_DAY,
  crunch: E.SPECIAL_DEFENSE_DOWN_HIT,
  mirrorcoat: E.MIRROR_COAT,
  psychup: E.PSYCH_UP,
  extremespeed: E.QUICK_ATTACK,
  ancientpower: E.ALL_STATS_UP_HIT,
  shadowball: E.SPECIAL_DEFENSE_DOWN_HIT,
  futuresight: E.FUTURE_SIGHT,
  rocksmash: E.DEFENSE_DOWN_HIT,
  whirlpool: E.TRAP,
  beatup: E.BEAT_UP,
  fakeout: E.FAKE_OUT,
  uproar: E.UPROAR,
  stockpile: E.STOCKPILE,
  spitup: E.SPIT_UP,
  swallow: E.SWALLOW,
  heatwave: E.BURN_HIT,
  hail: E.HAIL,
  torment: E.TORMENT,
  flatter: E.FLATTER,
  willowisp: E.WILL_O_WISP,
  memento: E.MEMENTO,
  facade: E.FACADE,
  focuspunch: E.FOCUS_PUNCH,
  smellingsalt: E.SMELLINGSALT,
  followme: E.FOLLOW_ME,
  naturepower: E.NATURE_POWER,
  charge: E.CHARGE,
  taunt: E.TAUNT,
  helpinghand: E.HELPING_HAND,
  trick: E.TRICK,
  roleplay: E.ROLE_PLAY,
  wish: E.WISH,
  assist: E.ASSIST,
  ingrain: E.INGRAIN,
  superpower: E.SUPERPOWER,
  magiccoat: E.MAGIC_COAT,
  recycle: E.RECYCLE,
  revenge: E.REVENGE,
  brickbreak: E.BRICK_BREAK,
  yawn: E.YAWN,
  knockoff: E.KNOCK_OFF,
  endeavor: E.ENDEAVOR,
  eruption: E.ERUPTION,
  skillswap: E.SKILL_SWAP,
  imprison: E.IMPRISON,
  refresh: E.REFRESH,
  grudge: E.GRUDGE,
  snatch: E.SNATCH,
  secretpower: E.SECRET_POWER,
  dive: E.SEMI_INVULNERABLE,
  armthrust: E.MULTI_HIT,
  camouflage: E.CAMOUFLAGE,
  tailglow: E.SPECIAL_ATTACK_UP_2,
  lusterpurge: E.SPECIAL_DEFENSE_DOWN_HIT,
  mistball: E.SPECIAL_ATTACK_DOWN_HIT,
  featherdance: E.ATTACK_DOWN_2,
  teeterdance: E.TEETER_DANCE,
  blazekick: E.BLAZE_KICK,
  mudsport: E.MUD_SPORT,
  iceball: E.ROLLOUT,
  needlearm: E.FLINCH_MINIMIZE_HIT,
  slackoff: E.RESTORE_HP,
  poisonfang: E.POISON_FANG,
  crushclaw: E.DEFENSE_DOWN_HIT,
  blastburn: E.RECHARGE,
  hydrocannon: E.RECHARGE,
  meteormash: E.ATTACK_UP_HIT,
  astonish: E.FLINCH_MINIMIZE_HIT,
  weatherball: E.WEATHER_BALL,
  aromatherapy: E.HEAL_BELL,
  faketears: E.SPECIAL_DEFENSE_DOWN_2,
  aircutter: E.HIGH_CRITICAL,
  overheat: E.OVERHEAT,
  odorsleuth: E.FORESIGHT,
  rocktomb: E.SPEED_DOWN_HIT,
  silverwind: E.ALL_STATS_UP_HIT,
  metalsound: E.SPECIAL_DEFENSE_DOWN_2,
  grasswhistle: E.SLEEP,
  tickle: E.TICKLE,
  cosmicpower: E.COSMIC_POWER,
  waterspout: E.ERUPTION,
  signalbeam: E.CONFUSE_HIT,
  shadowpunch: E.ALWAYS_HIT,
  extrasensory: E.FLINCH_MINIMIZE_HIT,
  skyuppercut: E.SKY_UPPERCUT,
  sandtomb: E.TRAP,
  sheercold: E.OHKO,
  muddywater: E.ACCURACY_DOWN_HIT,
  bulletseed: E.MULTI_HIT,
  aerialace: E.ALWAYS_HIT,
  iciclespear: E.MULTI_HIT,
  irondefense: E.DEFENSE_UP_2,
  block: E.MEAN_LOOK,
  howl: E.ATTACK_UP,
  frenzyplant: E.RECHARGE,
  bulkup: E.BULK_UP,
  bounce: E.SEMI_INVULNERABLE,
  mudshot: E.SPEED_DOWN_HIT,
  poisontail: E.POISON_TAIL,
  covet: E.THIEF,
  volttackle: E.DOUBLE_EDGE,
  magicalleaf: E.ALWAYS_HIT,
  watersport: E.WATER_SPORT,
  calmmind: E.CALM_MIND,
  leafblade: E.HIGH_CRITICAL,
  dragondance: E.DRAGON_DANCE,
  rockblast: E.MULTI_HIT,
  shockwave: E.ALWAYS_HIT,
  waterpulse: E.CONFUSE_HIT,
  doomdesire: E.FUTURE_SIGHT,
  psychoboost: E.OVERHEAT,
};

export function getEffect(moveId: string): E {
  return MOVE_TO_EFFECT[moveId] ?? E.HIT;
}
